# Generated by Django 5.1.2 on 2024-11-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='apellidos',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='posicion',
            field=models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], default='MED', max_length=3),
        ),
    ]
