# Generated by Django 5.1.2 on 2024-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesAPP', '0002_futbolista_apellidos_alter_futbolista_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbolista',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='futbolista',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
