# Generated by Django 5.1.2 on 2024-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesAPP', '0003_remove_futbolista_apellidos_futbolista_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolista',
            name='edad',
            field=models.DateField(),
        ),
    ]
