# Generated by Django 5.1.2 on 2024-11-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesAPP', '0004_alter_futbolista_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futbolista',
            old_name='edad',
            new_name='fecha_nac',
        ),
    ]
