# Generated by Django 5.1.2 on 2024-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionesAPP', '0005_rename_edad_futbolista_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='imagenFutbolista',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
